
enh: tf_masking1  # enhanced relation
enh_conf:
    loss_type: magnitude3 
    n_fft: 512
    hop_length: 256
    rnn_type: blstm
    layer: 3
    unit: 896
    dropout: 0.0 # in the pre-train enh model dropout is 0.5 and ,load the pre-train enh model tp joint mode, you should set dropout=0.0
    num_spk: 1
    mvn_dict: "/home/md510/w2020/espnet-recipe/enhancement_on_espnet2/data/data_Ach_train_8k_new_espnet2_2/cmvn_center_true3.dst" 
    nonlinear: mish
#
#init_param: exp_rats_Ach_waveform_8k_joint_enh_asr/input_wavefrom_se_model/valid.loss.best.pth:enh_model:enh_model

# ASR related
# network architecture
frontend: default # asr frontend relation 
frontend_conf:
   fs: 8000
   n_fft: 512
   n_mels: 80
   fmin: 0
   fmax: 4000
   htk: False
   #log_base: None

specaug: None
normalize: utterance_mvn

# encoder related
encoder: conformer
encoder_conf:
    output_size: 256
    attention_heads: 4
    linear_units: 2048
    num_blocks: 12
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.0
    input_layer: conv2d
    normalize_before: true
    concat_after: false
    positionwise_layer_type: linear
    macaron_style: true
    pos_enc_layer_type: rel_pos
    selfattention_layer_type: rel_selfattn
    activation_type: swish
    use_cnn_module: true
    cnn_module_kernel: 15

# decoder related
decoder: transformer
decoder_conf:
    attention_heads: 4
    linear_units: 2048
    num_blocks: 6
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    self_attention_dropout_rate: 0.0
    src_attention_dropout_rate: 0.0

#asr   hybrid enh/CTC/attention
# loss 
asr_model_conf:
    ctc_weight: 0.3
    lsm_weight: 0.1     # label smoothing option
    enh_weight: 0.0
    length_normalized_loss: false

unused_parameters: true


# minibatch related
batch_type: folded
batch_size: 32
num_att_plot: 0 # don't plot attention , because i pass uttid to the function
# optimization related
accum_grad: 2
grad_clip: 5
patience: 3
max_epoch: 100
val_scheduler_criterion:
    - valid
    - acc
best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 10

optim: adam
optim_conf:
    lr: 0.002
scheduler: warmuplr     # pytorch v1.1.0+ required
scheduler_conf:
    warmup_steps: 25000
