# network architecture
# encoder related
encoder: transformer
encoder_conf:
    output_size: 128    # dimension of attention
    attention_heads: 4
    linear_units: 256  # the number of units of position-wise feed forward
    num_blocks: 6      # the number of encoder blocks
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.0
    input_layer: conv2d # encoder architecture type
    normalize_before: true

# hybrid CTC/attention
model_conf:
    lsm_weight: 0.0     # label smoothing option
    length_normalized_loss: false

# minibatch related
batch_type: folded
batch_size: 64

# optimization related
accum_grad: 2
grad_clip: 5
patience: 0
max_epoch: 50
val_scheduler_criterion:
    - valid
    - acc
best_model_criterion:
-   - valid
    - acc
    - max

keep_nbest_models: 10

optim: adam
optim_conf:
    lr: 0.001
scheduler: warmuplr     # pytorch v1.1.0+ required
scheduler_conf:
    warmup_steps: 25000
