# enhancement related
enh: tf_masking_a
enh_conf:
    loss_type: mask_mse
    mask_type: psm
    n_fft: 256
    hop_length: 128
    rnn_type: blstm
    layer: 3
    unit: 896
    dropout: 0.5
    num_spk: 1
    nonlinear: relu

# kws related
# kws network architecture
# encoder related
encoder: transformer
encoder_conf:
    output_size: 64    # dimension of attention
    attention_heads: 4
    linear_units: 128  # the number of units of position-wise feed forward
    num_blocks: 3      # the number of encoder blocks
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.0
    input_layer: conv2d # encoder architecture type
    normalize_before: true

enh_kws_model_conf:
    enh_weight: 0.3
    length_normalized_loss: false

# minibatch related
batch_type: folded
batch_size: 32

# optimization related
accum_grad: 2
grad_clip: 5
patience: 0
max_epoch: 50
val_scheduler_criterion:
    - valid
    - acc
best_model_criterion:
-   - valid
    - acc
    - max

keep_nbest_models: 10

optim: adam
optim_conf:
    lr: 0.0002
scheduler: warmuplr     # pytorch v1.1.0+ required
scheduler_conf:
    warmup_steps: 25000
